spring:
  application:
    name: naverworksnotify
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${ip}/smart_tracker?allowMultiQueries=true
    username: root
    password: ${password}
