spring:
  application:
    name: naverworksnotify
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://58.121.186.18:33063/smart_tracker?allowMultiQueries=true
    username: root
    password: neotek
